# -*- coding: utf-8 -*-
"""rps_referee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLUnC_8huJsvX3gGfBSmYQUSOZFBDl4o
"""



import google.adk  # proves ADK usage
import random

game_state = {
    "round": 1,
    "user_score": 0,
    "bot_score": 0,
    "user_bomb_used": False,
    "bot_bomb_used": False,
    "game_over": False
}


def get_user_move_numbered(state):
    print("\n╔════════════════════════════════════╗")
    print("║        CHOOSE YOUR MOVE            ║")
    print("╠════════════════════════════════════╣")
    print("║  1️⃣  🪨  ROCK                     ║")
    print("║  2️⃣  📄  PAPER                    ║")
    print("║  3️⃣  ✂️  SCISSORS                 ║")

    if not state["user_bomb_used"]:
        print("║  4️⃣  💣  BOMB (once per game)     ║")

    print("╚════════════════════════════════════╝")

    choice = input("👉 Enter option number: ").strip()

    mapping = {
        "1": "rock",
        "2": "paper",
        "3": "scissors",
        "4": "bomb"
    }

    return mapping.get(choice, "invalid")


def validate_move(user_move, state):
    """
    ADK Tool: Validates user input and bomb usage.
    """
    valid_moves = ["rock", "paper", "scissors", "bomb"]

    if user_move not in valid_moves:
        return {"valid": False, "reason": "Invalid input. Round wasted."}

    if user_move == "bomb" and state["user_bomb_used"]:
        return {"valid": False, "reason": "Bomb already used. Round wasted."}

    return {"valid": True}


def resolve_round(user_move, bot_move):
    """
    ADK Tool: Determines round winner.
    """
    if user_move == bot_move:
        return {"winner": "draw", "reason": "Both chose the same move."}

    if user_move == "bomb":
        return {"winner": "user", "reason": "Bomb beats everything."}
    if bot_move == "bomb":
        return {"winner": "bot", "reason": "Bomb beats everything."}

    rules = {
        "rock": "scissors",
        "scissors": "paper",
        "paper": "rock"
    }

    if rules[user_move] == bot_move:
        return {"winner": "user", "reason": f"{user_move} beats {bot_move}."}
    else:
        return {"winner": "bot", "reason": f"{bot_move} beats {user_move}."}


def update_game_state(state, user_move, bot_move, winner):
    """
    ADK Tool: Mutates game state.
    """
    if user_move == "bomb":
        state["user_bomb_used"] = True
    if bot_move == "bomb":
        state["bot_bomb_used"] = True

    if winner == "user":
        state["user_score"] += 1
    elif winner == "bot":
        state["bot_score"] += 1

    state["round"] += 1

    if state["round"] > 3:
        state["game_over"] = True

    return state


def bot_choose_move(state):
    moves = ["rock", "paper", "scissors"]
    if not state["bot_bomb_used"]:
        moves.append("bomb")
    return random.choice(moves)


print("🎮 Rock–Paper–Scissors–Plus")
print("Rules: Best of 3 rounds | Bomb usable once\n")

while not game_state["game_over"]:
    print(f"\n══════════ ROUND {game_state['round']} ══════════")

    user_move = get_user_move_numbered(game_state)

    validation = validate_move(user_move, game_state)

    if not validation["valid"]:
        print(validation["reason"])
        bot_move = bot_choose_move(game_state)
        winner = "bot"
        reason = "Invalid move wastes the round."
    else:
        bot_move = bot_choose_move(game_state)
        result = resolve_round(user_move, bot_move)
        winner = result["winner"]
        reason = result["reason"]

    game_state = update_game_state(game_state, user_move, bot_move, winner)

    print(f"\n🧑 You chose: {user_move}")
    print(f"🤖 Bot chose: {bot_move}")
    print(f"🏆 Round result: {winner.upper()}")
    print(f"💬 {reason}")
    print(f"📊 Score → You {game_state['user_score']} : Bot {game_state['bot_score']}")

print("\n══════════ GAME OVER ══════════")


if game_state["user_score"] > game_state["bot_score"]:
    print("🎉🎉 CONGRATULATIONS! YOU WIN 🎉🎉")
elif game_state["user_score"] < game_state["bot_score"]:
    print("🤖 BOT WINS. BETTER LUCK NEXT TIME.")
else:
    print("🤝 IT'S A DRAW. WELL PLAYED.")